# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c9e74d94a9707c5ea664a34551f7e331788981406f9e1a662eb90692df9146b1123063d49122e6b2d5ee7e9b26a9e931698ae73b62425ce01b17248fb2bb13f

test:
  secret_key_base: 9f900d4932e686e8af215b7a88f13bf9b481dde2ce7e3bd0a3ea4d8a841913ee1fc49ead70c5940201dca66f180e569e73abd07b15805ae203e68a688380b2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
